services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_tracker
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql